#!/usr/bin/env python3
# coding = utf-8
# author = listenerri
# maintainer = listenerri

Action_2_Delivery_Template = {
    "addAttachment": "{user} 添加了附件\n看板：{board}\n列表：{list}\n任务：{card}",
    "deleteAttachment": "{user} 移除了附件\n看板：{board}\n列表：{list}\n任务：{card}",
    "addSubtask": "{user} 添加了子任务\n看板：{board}\n列表：{list}\n任务：{card}",
    "addedLabel": "{user} 添加了标签\n看板：{board}\n列表：{list}\n任务：{card}",
    "removedLabel": "{user} 移除了标签\n看板：{board}\n列表：{list}\n任务：{card}",
    "addChecklist": "{user} 添加了待办清单\n看板：{board}\n列表：{list}\n任务：{card}",
    "removeChecklist": "{user} 移除了待办清单\n看板：{board}\n列表：{list}\n任务：{card}",
    "addChecklistItem": "{user} 添加了待办清单项\n看板：{board}\n列表：{list}\n任务：{card}",
    "checkedItem": "{user} 完成了待办清单项\n看板：{board}\n列表：{list}\n任务：{card}",
    "uncheckedItem": "{user} 修改/复原了待办清单项\n看板：{board}\n列表：{list}\n任务：{card}",
    "removedChecklistItem": "{user} 移除了待办清单项\n看板：{board}\n列表：{list}\n任务：{card}",
    "completeChecklist": "{user} 完成了清单\n看板：{board}\n列表：{list}\n任务：{card}",
    "uncompleteChecklist": "{user} 复原了清单\n看板：{board}\n列表：{list}\n任务：{card}",
    "addComment": "{user} 评论了任务\n看板：{board}\n列表：{list}\n任务：{card}\n评论内容：{comment}",
    "editComment": "{user} 编辑了任务评论\n看板：{board}\n列表：{list}\n任务：{card}\n评论内容：{comment}",
    "deleteComment": "{user} 删除任务评论\n看板：{board}\n列表：{list}\n任务：{card}",
    "createBoard": "{user} 创建了看板\n看板：{board}",
    "archivedBoard": "{user} 归档了看板\n看板：{board}",
    "removeBoard": "{user} 删除了看板\n看板：{board}",
    "createSwimlane": "{user} 创建了泳道\n看板：{board}",
    "archivedSwimlane": "{user} 归档了泳道\n看板：{board}\n列表：{list}\n任务：{card}",
    "createList": "{user} 创建了列表\n看板：{board}\n列表：{list}",
    "archivedList": "{user} 归档了列表\n看板：{board}\n列表：{list}\n任务：{card}",
    "removeList": "{user} 删除了列表\n看板：{board}\n列表：{list}\n任务：{card}",
    "createCard": "{user} 创建了任务\n看板：{board}\n列表：{list}\n任务：{card}",
    "archivedCard": "{user} 归档了任务\n看板：{board}\n列表：{list}\n任务：{card}",
    "restoredCard": "{user} 恢复了任务\n看板：{board}\n列表：{list}\n任务：{card}",
    "createCustomField": "{user} 创建了自定义字段\n看板：{board}\n列表：{list}\n任务：{card}",
    "deleteCustomField": "{user} 删除了自定义字段\n看板：{board}\n列表：{list}\n任务：{card}",
    "setCustomField": "{user} 修改了自定义字段\n看板：{board}\n列表：{list}\n任务：{card}",
    "addBoardMember": "{user} 添加了看板成员\n看板：{board}",
    "removeBoardMember": "{user} 移除了看板成员\n看板：{board}",
    "joinMember": "{user} 增加了任务成员\n看板：{board}\n列表：{list}\n任务：{card}",
    "unjoinMember": "{user} 移除了任务成员\n看板：{board}\n列表：{list}\n任务：{card}",
    "joinAssignee": "{user} 增加了任务被指派成员\n看板：{board}\n列表：{list}\n任务：{card}",
    "unjoinAssignee": "{user} 移除了任务被指派成员\n看板：{board}\n列表：{list}\n任务：{card}",
    "moveCard": "{user} 移动了任务\n看板：{board}\n列表：{list}\n任务：{card}",
    "moveCardBoard": "{user} 移动了任务\n看板：{board}\n列表：{list}\n任务：{card}",
    "a-dueAt": "{user} 修改了任务到期时间\n看板：{board}\n列表：{list}\n任务：{card}",
    "a-endAt": "{user} 修改了任务结束时间\n看板：{board}\n列表：{list}\n任务：{card}",
    "a-startAt": "{user} 修改了任务开始时间\n看板：{board}\n列表：{list}\n任务：{card}",
    "a-receivedAt": "{user} 修改了任务接收时间\n看板：{board}\n列表：{list}\n任务：{card}",
    "newDue": "{user} 任务到期提醒\n看板：{board}\n列表：{list}\n任务：{card}",
    "withDue": "{user} 任务到期提醒\n看板：{board}\n列表：{list}\n任务：{card}",
    "almostdue": "{user} 任务到期提醒\n看板：{board}\n列表：{list}\n任务：{card}",
    "pastdue": "{user} 任务到期提醒\n看板：{board}\n列表：{list}\n任务：{card}",
    "duenow": "{user} 任务到期提醒\n看板：{board}\n列表：{list}\n任务：{card}"
}
